CC=g++
CFLAGS=-Wall -Werror
BINARIES=wcat wgrep wzip wunzip
all: wcat wgrep wzip wunzip
wcat: wcat.cpp
	$(CC) $(CFLAGS) wcat.cpp -o wcat
wgrep: wgrep.cpp
	$(CC) $(CFLAGS) wgrep.cpp -o wgrep
wzip: wzip.cpp
	$(CC) $(CFLAGS) wzip.cpp -o wzip
wunzip: wunzip.cpp
	$(CC) $(CFLAGS) wunzip.cpp -o wunzip